"""Reminder schedule generation and (stub) push.

The brain owns the schedule. Actual delivery is the phone client's job — it
will receive the next 72h of rows and register them with
``UNUserNotificationCenter`` so they fire reliably even when the brain is
asleep, the network is down, or the phone is offline.

This module today:
  * Generates the per-event row set (T-30, T-5, +0, +5, +10, +15).
  * Generates the daily morning-summary row (one per day, includes that
    day's event list).
  * Persists schedules as JSON sidecars in vault/_reminders/.
  * Provides a `push_to_phone` stub that logs what *would* be pushed.

When the phone exists, swap the stub for an HTTPS POST over Tailscale.
"""

from __future__ import annotations

import logging
from datetime import datetime, timedelta, time
from pathlib import Path
from typing import Iterable
from zoneinfo import ZoneInfo

from . import vault
from .schemas import CalendarEvent, ReminderRow, ReminderKind


log = logging.getLogger(__name__)


# Offsets relative to event start, in minutes. Negative = before.
_STRIKE_PLAN: list[tuple[ReminderKind, int]] = [
    (ReminderKind.HEADS_UP_30, -30),
    (ReminderKind.PRE_5, -5),
    (ReminderKind.STRIKE_0, 0),
    (ReminderKind.STRIKE_5, 5),
    (ReminderKind.STRIKE_10, 10),
    (ReminderKind.STRIKE_15, 15),
]


def build_event_schedule(event: CalendarEvent) -> list[ReminderRow]:
    """Return the 6-row reminder schedule for a single event.

    Morning summary is intentionally NOT here — it's per-day, not per-event,
    and is generated by `build_morning_summary` below.
    """
    rows: list[ReminderRow] = []
    for kind, offset_min in _STRIKE_PLAN:
        fire_at = event.starts_at + timedelta(minutes=offset_min)
        rows.append(
            ReminderRow(
                event_id=event.id,
                kind=kind,
                fire_at=fire_at,
                tz=event.tz,
                body=_body_for(kind, event),
            )
        )
    return rows


def _body_for(kind: ReminderKind, e: CalendarEvent) -> str:
    when = e.starts_at.strftime("%-I:%M %p")
    title = e.title
    if kind is ReminderKind.HEADS_UP_30:
        return f"In 30 minutes: {title} at {when}."
    if kind is ReminderKind.PRE_5:
        return f"5 minutes: {title} at {when}."
    if kind is ReminderKind.STRIKE_0:
        return f"{title} is starting now. Tap OK when you see this."
    if kind is ReminderKind.STRIKE_5:
        return f"Still on? {title} started 5 minutes ago. Tap OK."
    if kind is ReminderKind.STRIKE_10:
        return f"Reminder: {title} — 10 minutes ago. Tap OK."
    if kind is ReminderKind.STRIKE_15:
        return f"Final reminder. {title}. Tap OK or I'll log it as missed."
    return title


def build_morning_summary(
    events_today: list[CalendarEvent],
    missed_yesterday: list[CalendarEvent],
    summary_date: datetime,
    summary_time_local: str,
    tz: ZoneInfo,
) -> ReminderRow:
    """One summary row for a given day. Fires at `summary_time_local` in `tz`.

    `summary_date` carries the date; its tzinfo is replaced by `tz`.
    """
    hh, mm = (int(x) for x in summary_time_local.split(":"))
    fire_at = datetime.combine(
        summary_date.date(),
        time(hour=hh, minute=mm),
        tzinfo=tz,
    )

    body = _compose_summary_body(events_today, missed_yesterday)
    return ReminderRow(
        event_id=f"summary-{summary_date.date().isoformat()}",
        kind=ReminderKind.MORNING_SUMMARY,
        fire_at=fire_at,
        tz=str(tz),
        body=body,
    )


def _compose_summary_body(events_today: list[CalendarEvent], missed_yesterday: list[CalendarEvent]) -> str:
    if not events_today:
        head = "Good morning. No events today."
    else:
        bits = [f"{e.starts_at.strftime('%-I:%M %p')} {e.title}" for e in events_today[:5]]
        more = "" if len(events_today) <= 5 else f", and {len(events_today) - 5} more"
        head = "Good morning. Today: " + ", ".join(bits) + more + "."
    if missed_yesterday:
        miss_bits = ", ".join(e.title for e in missed_yesterday)
        head += f" Yesterday missed: {miss_bits}. Tap to reschedule."
    return head


def persist_event_schedule(vault_path: Path, event: CalendarEvent, rows: Iterable[ReminderRow]) -> Path:
    payload = [
        {
            "event_id": r.event_id,
            "kind": r.kind.value,
            "fire_at": r.fire_at.isoformat(),
            "tz": r.tz,
            "body": r.body,
            "status": r.status,
        }
        for r in rows
    ]
    return vault.write_reminder_schedule(vault_path, event.id, payload)


def push_to_phone(rows: Iterable[ReminderRow]) -> None:
    """Stub. Once the phone client and the Tailscale-reachable endpoint exist,
    this becomes an HTTPS POST that the phone uses to register notifications
    with UNUserNotificationCenter. For now we just log the schedule so the
    boss can see in the activity log what *would* have fired.
    """
    for r in rows:
        log.info("would-push reminder kind=%s event=%s fire_at=%s body=%r", r.kind, r.event_id, r.fire_at, r.body)
