"""
test_v012_no_account.py — TDD regression suite for v0.1.2.

All tests in this file were written RED first (against the v0.1.1 code that
still had `ensure_calendar` and `tell account` everywhere), then turned GREEN
by the v0.1.2 patch.

Discipline:
- No real osascript. All Calendar.app calls mocked.
- No `tell account` anywhere in AppleScript generated by this module.
- Startup with a missing calendar must exit gracefully, not crash-loop.
"""

from __future__ import annotations

import sys
import textwrap
from pathlib import Path
from unittest.mock import MagicMock, call, patch

import pytest

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _make_event_md(event_id="2026-09-15-meeting-with-myself"):
    return textwrap.dedent(f"""\
        ---
        id: {event_id}
        title: meeting with myself
        starts_at: '2026-09-15T09:00:00-04:00'
        ends_at: '2026-09-15T09:30:00-04:00'
        tz: America/New_York
        duration_minutes: 30
        ---
    """)


_DARWIN_ONLY = pytest.mark.skipif(
    sys.platform != "darwin", reason="AppleScript only available on macOS"
)


# ---------------------------------------------------------------------------
# TDD-1  ensure_calendar no longer exists in the module
# ---------------------------------------------------------------------------

class TestEnsureCalendarDeleted:
    """ensure_calendar must be fully removed from applescript.py."""

    def test_import_does_not_expose_ensure_calendar(self):
        """Importing mac_calendar_bridge.applescript must NOT expose ensure_calendar."""
        import mac_calendar_bridge.applescript as as_mod
        assert not hasattr(as_mod, "ensure_calendar"), (
            "ensure_calendar still exists in applescript.py — it must be deleted in v0.1.2"
        )

    def test_watcher_does_not_import_ensure_calendar(self):
        """watcher.py must not import ensure_calendar."""
        import mac_calendar_bridge.watcher as watcher_mod
        assert not hasattr(watcher_mod, "ensure_calendar"), (
            "watcher.py still imports ensure_calendar — the import must be removed in v0.1.2"
        )


# ---------------------------------------------------------------------------
# TDD-2  verify_calendar_exists returns bool from AppleScript
# ---------------------------------------------------------------------------

@_DARWIN_ONLY
class TestVerifyCalendarExists:
    """verify_calendar_exists(calendar_name) must run an AppleScript and return bool."""

    def test_returns_true_when_calendar_found(self):
        from mac_calendar_bridge.applescript import verify_calendar_exists
        with patch(
            "mac_calendar_bridge.applescript.run_applescript",
            return_value="true",
        ):
            result = verify_calendar_exists("Homunculus")
        assert result is True

    def test_returns_false_when_calendar_missing(self):
        from mac_calendar_bridge.applescript import verify_calendar_exists
        with patch(
            "mac_calendar_bridge.applescript.run_applescript",
            return_value="false",
        ):
            result = verify_calendar_exists("Homunculus")
        assert result is False

    def test_script_contains_exists_calendar(self):
        """The AppleScript must use 'exists calendar "<name>"'."""
        from mac_calendar_bridge.applescript import verify_calendar_exists
        with patch("mac_calendar_bridge.applescript.run_applescript") as mock_run:
            mock_run.return_value = "true"
            verify_calendar_exists("Homunculus")
        script = mock_run.call_args[0][0]
        assert 'exists calendar "Homunculus"' in script

    def test_script_does_not_contain_tell_account(self):
        """verify_calendar_exists must NOT use 'tell account' — invalid AppleScript."""
        from mac_calendar_bridge.applescript import verify_calendar_exists
        with patch("mac_calendar_bridge.applescript.run_applescript") as mock_run:
            mock_run.return_value = "true"
            verify_calendar_exists("Homunculus")
        script = mock_run.call_args[0][0]
        assert "tell account" not in script, (
            "REGRESSION: verify_calendar_exists generated a 'tell account' line "
            "which is not valid AppleScript for Calendar.app"
        )

    def test_returns_bool_type(self):
        """Return value must be exactly bool True or False, not a string."""
        from mac_calendar_bridge.applescript import verify_calendar_exists
        with patch("mac_calendar_bridge.applescript.run_applescript", return_value="true"):
            result = verify_calendar_exists("Homunculus")
        assert isinstance(result, bool)

    def test_no_account_name_parameter(self):
        """verify_calendar_exists must accept only calendar_name — no account_name."""
        from mac_calendar_bridge.applescript import verify_calendar_exists
        import inspect
        sig = inspect.signature(verify_calendar_exists)
        assert "account_name" not in sig.parameters, (
            "verify_calendar_exists must not accept account_name — "
            "Calendar.app has no account concept in AppleScript"
        )


# ---------------------------------------------------------------------------
# TDD-3  push_event has no tell account
# ---------------------------------------------------------------------------

@_DARWIN_ONLY
class TestPushEventNoAccount:
    """push_event must NOT generate 'tell account' in its AppleScript."""

    def _make_event(self):
        from datetime import datetime, timezone
        from mac_calendar_bridge.vault_reader import EventRecord
        return EventRecord(
            event_id="2026-09-15-meeting-with-myself",
            title="meeting with myself",
            starts_at=datetime(2026, 9, 15, 13, 0, tzinfo=timezone.utc),
            ends_at=datetime(2026, 9, 15, 13, 30, tzinfo=timezone.utc),
            tz="America/New_York",
            duration_minutes=30,
            source_path=Path("/tmp/fake.md"),
        )

    def test_push_event_script_has_no_tell_account(self):
        from mac_calendar_bridge.applescript import push_event
        event = self._make_event()
        with patch("mac_calendar_bridge.applescript.run_applescript") as mock_run:
            mock_run.return_value = ""
            push_event(event, "Homunculus")
        script = mock_run.call_args[0][0]
        assert "tell account" not in script, (
            "REGRESSION: push_event generated a 'tell account' line "
            "which is not valid AppleScript for Calendar.app"
        )

    def test_push_event_script_has_tell_calendar(self):
        """push_event must use 'tell calendar \"Homunculus\"' directly."""
        from mac_calendar_bridge.applescript import push_event
        event = self._make_event()
        with patch("mac_calendar_bridge.applescript.run_applescript") as mock_run:
            mock_run.return_value = ""
            push_event(event, "Homunculus")
        script = mock_run.call_args[0][0]
        assert 'tell calendar "Homunculus"' in script

    def test_push_event_no_account_name_parameter(self):
        """push_event must not accept account_name after v0.1.2."""
        from mac_calendar_bridge.applescript import push_event
        import inspect
        sig = inspect.signature(push_event)
        assert "account_name" not in sig.parameters, (
            "push_event still has account_name parameter — must be removed in v0.1.2"
        )


# ---------------------------------------------------------------------------
# TDD-4  query_pushed_event_ids has no tell account
# ---------------------------------------------------------------------------

@_DARWIN_ONLY
class TestQueryPushedEventIdsNoAccount:
    """query_pushed_event_ids must NOT generate 'tell account' in its AppleScript."""

    def test_query_script_has_no_tell_account(self):
        from mac_calendar_bridge.applescript import query_pushed_event_ids
        with patch(
            "mac_calendar_bridge.applescript.run_applescript",
            return_value="",
        ) as mock_run:
            query_pushed_event_ids("Homunculus", "Monday, September 15, 2026 at 12:00 AM")
        script = mock_run.call_args[0][0]
        assert "tell account" not in script, (
            "REGRESSION: query_pushed_event_ids generated a 'tell account' line "
            "which is not valid AppleScript for Calendar.app"
        )

    def test_query_script_has_tell_calendar(self):
        from mac_calendar_bridge.applescript import query_pushed_event_ids
        with patch(
            "mac_calendar_bridge.applescript.run_applescript",
            return_value="",
        ) as mock_run:
            query_pushed_event_ids("Homunculus", "Monday, September 15, 2026 at 12:00 AM")
        script = mock_run.call_args[0][0]
        assert 'tell calendar "Homunculus"' in script

    def test_query_no_account_name_parameter(self):
        """query_pushed_event_ids must not accept account_name after v0.1.2."""
        from mac_calendar_bridge.applescript import query_pushed_event_ids
        import inspect
        sig = inspect.signature(query_pushed_event_ids)
        assert "account_name" not in sig.parameters, (
            "query_pushed_event_ids still has account_name — must be removed in v0.1.2"
        )


# ---------------------------------------------------------------------------
# TDD-5  Regression guard — no tell account in any .py source file
# ---------------------------------------------------------------------------

class TestRegressionGuardNoTellAccount:
    """
    Static scan: zero occurrences of 'tell account' in any .py file under
    src/mac_calendar_bridge/. This catches the exact pattern that caused the
    v0.1.1 crash-loop and prevents it from ever returning.
    """

    def test_no_tell_account_in_source_tree(self):
        # Scan .py source for "tell account" on lines that are part of an
        # f-string (i.e., would be rendered into actual AppleScript at runtime).
        # Pure Python comment lines (# ...) and plain docstring prose are OK
        # because they document WHY the construct is invalid.
        # We flag: lines containing "tell account" AND an f-string opening
        # quote on the same line (pattern: f" or f').
        import re
        src_root = Path(__file__).parent.parent / "src" / "mac_calendar_bridge"
        violations = []
        for py_file in src_root.rglob("*.py"):
            content = py_file.read_text(encoding="utf-8")
            for lineno, line in enumerate(content.splitlines(), 1):
                stripped = line.strip()
                if "tell account" not in line:
                    continue
                # Skip pure comment lines
                if stripped.startswith("#"):
                    continue
                # Skip lines that have no f-string indicator
                # (prose in docstrings or module-level strings)
                if not re.search(r"\bf['\"]", line):
                    continue
                violations.append(f"{py_file}:{lineno}: {stripped}")

        assert not violations, (
            "REGRESSION: 'tell account' found inside an f-string in source. "
            "Calendar.app does not support this AppleScript construct. "
            "Remove it from:\n" + "\n".join(violations)
        )


# ---------------------------------------------------------------------------
# TDD-6  watcher.main() — missing calendar → graceful exit, not crash loop
# ---------------------------------------------------------------------------

class TestWatcherMissingCalendarExitsGracefully:
    """
    If verify_calendar_exists returns False at startup, watcher.main() must:
      - Log the actionable error message.
      - Exit with sys.exit(1) or equivalent non-zero.
      - NOT enter the watch loop (no Observer started).
    """

    def test_exits_with_sysexit_when_calendar_missing(self):
        with (
            patch("mac_calendar_bridge.watcher.verify_calendar_exists", return_value=False),
            patch("mac_calendar_bridge.watcher.configure_logging"),
            patch("mac_calendar_bridge.watcher.cold_boot_sweep") as mock_sweep,
            pytest.raises(SystemExit) as exc_info,
        ):
            from mac_calendar_bridge.watcher import main
            main()

        assert exc_info.value.code != 0, "sys.exit must be non-zero when calendar is missing"
        mock_sweep.assert_not_called()

    def test_logs_actionable_message_when_calendar_missing(self, caplog):
        import logging
        with (
            patch("mac_calendar_bridge.watcher.verify_calendar_exists", return_value=False),
            patch("mac_calendar_bridge.watcher.configure_logging"),
            caplog.at_level(logging.ERROR, logger="mac_calendar_bridge.watcher"),
            pytest.raises(SystemExit),
        ):
            from mac_calendar_bridge.watcher import main
            main()

        combined = " ".join(caplog.messages)
        # The message must tell Thomas what to do
        assert "Create" in combined or "create" in combined or "iCloud" in combined, (
            f"Log message is not actionable. Got: {caplog.messages}"
        )

    def test_observer_not_started_when_calendar_missing(self):
        with (
            patch("mac_calendar_bridge.watcher.verify_calendar_exists", return_value=False),
            patch("mac_calendar_bridge.watcher.configure_logging"),
            patch("mac_calendar_bridge.watcher.Observer") as mock_observer_cls,
            pytest.raises(SystemExit),
        ):
            from mac_calendar_bridge.watcher import main
            main()

        # Observer must never have been instantiated or started
        mock_observer_cls.assert_not_called()


# ---------------------------------------------------------------------------
# TDD-6b  watcher.main() — calendar exists → proceeds normally
# ---------------------------------------------------------------------------

class TestWatcherCalendarExistsProceedsNormally:
    """When verify_calendar_exists returns True, main() proceeds past the check."""

    def test_cold_boot_sweep_called_when_calendar_exists(self, tmp_path):
        with (
            patch("mac_calendar_bridge.watcher.verify_calendar_exists", return_value=True),
            patch("mac_calendar_bridge.watcher.configure_logging"),
            patch("mac_calendar_bridge.watcher.cold_boot_sweep", return_value=0) as mock_sweep,
            patch("mac_calendar_bridge.watcher.Observer") as mock_obs_cls,
        ):
            mock_obs = MagicMock()
            mock_obs_cls.return_value = mock_obs
            # Make is_alive() return False immediately so the loop exits
            mock_obs.is_alive.return_value = False

            from mac_calendar_bridge.watcher import main
            main()  # should NOT raise SystemExit

        mock_sweep.assert_called_once()


# ---------------------------------------------------------------------------
# TDD-7  Config no longer has calendar_account
# ---------------------------------------------------------------------------

class TestConfigNoCalendarAccount:
    """Config.from_env() must NOT have a calendar_account field in v0.1.2."""

    def test_config_has_no_calendar_account_field(self):
        from mac_calendar_bridge.config import Config
        cfg = Config.from_env()
        assert not hasattr(cfg, "calendar_account"), (
            "Config still has calendar_account field — must be removed in v0.1.2"
        )

    def test_bridge_calendar_account_env_var_has_no_effect(self, monkeypatch):
        """Setting BRIDGE_CALENDAR_ACCOUNT must not cause an error (var is ignored)."""
        monkeypatch.setenv("BRIDGE_CALENDAR_ACCOUNT", "iCloud")
        from mac_calendar_bridge.config import Config
        cfg = Config.from_env()
        # Should not raise; calendar_account field should simply not exist
        assert not hasattr(cfg, "calendar_account")
