#!/bin/bash
# Sprite M2 install script
# Copies the watcher entry point to ~/.local/bin/ and the plist to
# ~/Library/LaunchAgents/. Does NOT load the plist — see FDA_SETUP.md first.
#
# Usage: bash deploy/install.sh [--venv-python /path/to/python3]
#
# Portability: pure bash, no Mac-only tools required. On Linux the launchd
# section is skipped; the systemd unit is printed for manual installation.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SPRITE_REPO="$(dirname "$SCRIPT_DIR")"

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

BIN_DIR="${HOME}/.local/bin"
LIB_DIR="${HOME}/.local/lib/sprite"
PLIST_DST="${HOME}/Library/LaunchAgents/com.sprite.watcher.plist"
PLIST_SRC="${SCRIPT_DIR}/com.sprite.watcher.plist"
VENV_PYTHON="${1:-python3}"

# ---------------------------------------------------------------------------
# Create directories
# ---------------------------------------------------------------------------

mkdir -p "$BIN_DIR" "$LIB_DIR"
echo "[install] Created $BIN_DIR and $LIB_DIR"

# ---------------------------------------------------------------------------
# Install Sprite as an editable pip package into a dedicated venv
# (boot volume, not /Volumes/GIT which is nosuid)
# ---------------------------------------------------------------------------

SPRITE_VENV="${HOME}/.local/lib/sprite/venv"
if [ ! -d "$SPRITE_VENV" ]; then
    echo "[install] Creating venv at $SPRITE_VENV"
    "$VENV_PYTHON" -m venv "$SPRITE_VENV"
fi
"$SPRITE_VENV/bin/pip" install --quiet -e "$SPRITE_REPO"
echo "[install] Sprite package installed into $SPRITE_VENV"

# ---------------------------------------------------------------------------
# Write the watcher shell script to ~/.local/bin/sprite_watcher.sh
# The shebang uses the venv Python so launchd resolves it even without
# activating the venv.
# ---------------------------------------------------------------------------

WATCHER_SH="${BIN_DIR}/sprite_watcher.sh"
cat > "$WATCHER_SH" <<'SHEOF'
#!/bin/bash
# Auto-generated by install.sh — do not edit by hand.
exec "${HOME}/.local/lib/sprite/venv/bin/python" -m sprite.watcher "$@"
SHEOF
chmod +x "$WATCHER_SH"
echo "[install] Watcher script written to $WATCHER_SH"

# ---------------------------------------------------------------------------
# Install the launchd plist (macOS only) — do NOT load it yet
# ---------------------------------------------------------------------------

if [[ "$(uname)" == "Darwin" ]]; then
    mkdir -p "${HOME}/Library/LaunchAgents"
    cp "$PLIST_SRC" "$PLIST_DST"
    # Patch the plist to use the actual username.
    sed -i '' "s|/Users/fourierflight/|${HOME}/|g" "$PLIST_DST"
    echo "[install] Plist installed at $PLIST_DST"
    echo ""
    echo "======================================================================"
    echo "  IMPORTANT: Do not load the plist yet!"
    echo "  You must grant Full Disk Access FIRST."
    echo ""
    echo "  Steps:"
    echo "    1. Open System Settings → Privacy & Security → Full Disk Access"
    echo "    2. Click '+' and add: $WATCHER_SH"
    echo "       (if the shell script is not grantable, add the venv Python:"
    echo "        ${HOME}/.local/lib/sprite/venv/bin/python)"
    echo "    3. Then run:"
    echo "       launchctl load $PLIST_DST"
    echo "    4. Check it started:"
    echo "       launchctl list | grep sprite"
    echo "       tail -f /tmp/sprite_watcher.log"
    echo "======================================================================"
else
    echo ""
    echo "======================================================================"
    echo "  Linux detected — systemd unit available at:"
    echo "  ${SCRIPT_DIR}/sprite-watcher.service"
    echo ""
    echo "  To install:"
    echo "    cp ${SCRIPT_DIR}/sprite-watcher.service ~/.config/systemd/user/"
    echo "    systemctl --user daemon-reload"
    echo "    systemctl --user enable sprite-watcher"
    echo "    systemctl --user start sprite-watcher"
    echo "======================================================================"
fi

# ---------------------------------------------------------------------------
# Download whisper model if not present
# ---------------------------------------------------------------------------

MODELS_DIR="${HOME}/sprite/models"
mkdir -p "$MODELS_DIR"
MODEL_PATH="${MODELS_DIR}/ggml-small.en.bin"

if [ ! -f "$MODEL_PATH" ]; then
    echo ""
    echo "[install] whisper.cpp model not found at $MODEL_PATH"
    echo "  To download:"
    echo "    brew install whisper-cpp   # installs the binary"
    echo "    # Model download (run once):"
    echo "    whisper-cpp-download-ggml-model small.en"
    echo "    # Then move it:"
    echo "    mv ~/Library/Caches/whisper/ggml-small.en.bin $MODEL_PATH"
    echo ""
    echo "  Or manually from: https://huggingface.co/ggerganov/whisper.cpp"
else
    echo "[install] Model found at $MODEL_PATH — good."
fi

echo ""
echo "[install] Done. See docs/FDA_SETUP.md and docs/FIRST_RUN.md for next steps."
