#!/bin/bash
# mac_notifier v0.1.0 install script
#
# Installs mac_notifier to the boot volume (required — repo lives on /Volumes/GIT
# which is nosuid; launchd cannot exec scripts from there).
#
# What this does:
#   1. Creates ~/.local/lib/mac_notifier/venv (Python venv on boot volume)
#   2. pip-installs mac-notifier (editable) from the repo
#   3. Writes ~/.local/bin/mac_notifier.sh (entry point)
#   4. Copies the launchd plist to ~/Library/LaunchAgents/ (macOS only)
#      - patches /Users/fourierflight → $HOME
#
# Usage:
#   bash deploy/install.sh [--venv-python /path/to/python3]
#
# After install, on macOS:
#   launchctl load ~/Library/LaunchAgents/com.homunculus.mac_notifier.plist
#   launchctl list | grep mac_notifier
#   tail -f /tmp/mac_notifier.log

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
NOTIFIER_REPO="$(dirname "$SCRIPT_DIR")"

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

BIN_DIR="${HOME}/.local/bin"
LIB_DIR="${HOME}/.local/lib/mac_notifier"
PLIST_SRC="${SCRIPT_DIR}/com.homunculus.mac_notifier.plist"
PLIST_DST="${HOME}/Library/LaunchAgents/com.homunculus.mac_notifier.plist"
VENV_PYTHON="${1:-python3}"

# Handle --venv-python flag
if [[ "${1:-}" == "--venv-python" && -n "${2:-}" ]]; then
    VENV_PYTHON="$2"
fi

# ---------------------------------------------------------------------------
# Create directories
# ---------------------------------------------------------------------------

mkdir -p "$BIN_DIR" "$LIB_DIR"
echo "[install] Created $BIN_DIR and $LIB_DIR"

# ---------------------------------------------------------------------------
# Create venv and install mac-notifier (editable)
# (boot volume so launchd can exec from here)
# ---------------------------------------------------------------------------

NOTIFIER_VENV="${LIB_DIR}/venv"
if [ ! -d "$NOTIFIER_VENV" ]; then
    echo "[install] Creating venv at $NOTIFIER_VENV"
    "$VENV_PYTHON" -m venv "$NOTIFIER_VENV"
fi

echo "[install] Installing mac-notifier into $NOTIFIER_VENV"
"$NOTIFIER_VENV/bin/pip" install --quiet -e "$NOTIFIER_REPO"
echo "[install] Package installed."

# ---------------------------------------------------------------------------
# Write the entry-point shell script to ~/.local/bin/
# ---------------------------------------------------------------------------

ENTRY_SH="${BIN_DIR}/mac_notifier.sh"
cat > "$ENTRY_SH" <<'SHEOF'
#!/bin/bash
# Auto-generated by install.sh — do not edit by hand.
exec "${HOME}/.local/lib/mac_notifier/venv/bin/python" -m mac_notifier.poller "$@"
SHEOF
chmod +x "$ENTRY_SH"
echo "[install] Entry point written to $ENTRY_SH"

# ---------------------------------------------------------------------------
# Install launchd plist (macOS only)
# ---------------------------------------------------------------------------

if [[ "$(uname)" == "Darwin" ]]; then
    mkdir -p "${HOME}/Library/LaunchAgents"
    cp "$PLIST_SRC" "$PLIST_DST"
    # Patch the hardcoded /Users/fourierflight to the actual $HOME
    sed -i '' "s|/Users/fourierflight/|${HOME}/|g" "$PLIST_DST"
    echo "[install] Plist installed at $PLIST_DST"

    if plutil -lint "$PLIST_DST" >/dev/null 2>&1; then
        echo "[install] plutil lint: OK"
    else
        echo "[install] WARNING: plutil found issues in the plist — check $PLIST_DST"
    fi

    echo ""
    echo "======================================================================"
    echo "  mac_notifier installed. To start:"
    echo ""
    echo "    launchctl load $PLIST_DST"
    echo "    launchctl list | grep mac_notifier"
    echo "    tail -f /tmp/mac_notifier.log"
    echo ""
    echo "  No Automation permission needed — display notification does not"
    echo "  require System Settings → Privacy & Security → Automation."
    echo ""
    echo "  See docs/FIRST_RUN.md for the full walkthrough."
    echo "======================================================================"
else
    echo ""
    echo "======================================================================"
    echo "  Linux detected — launchd is not available."
    echo ""
    echo "  For Linux, use the systemd unit:"
    echo "    cp deploy/mac-notifier.service ~/.config/systemd/user/"
    echo "    systemctl --user daemon-reload"
    echo "    systemctl --user enable --now mac-notifier"
    echo ""
    echo "  Note: osascript notifications are macOS-only. On Linux, the poller"
    echo "  runs but notifications are logged rather than displayed."
    echo "======================================================================"
fi

echo ""
echo "[install] Done. See docs/FIRST_RUN.md for next steps."
