#!/bin/bash
# mac_notes_bridge v0.1.0 install script
#
# Installs the bridge to the boot volume (required — repo lives on /Volumes/GIT
# which is nosuid; launchd cannot exec scripts from there).
#
# What this does:
#   1. Creates ~/.local/lib/mac_notes_bridge/venv (Python venv on boot volume)
#   2. pip-installs mac-notes-bridge (editable) from the repo
#   3. Writes ~/.local/bin/mac_notes_bridge.sh (entry point)
#   4. Copies the launchd plist to ~/Library/LaunchAgents/ (macOS only)
#      - patches /Users/fourierflight → $HOME
#      - does NOT load the plist (you must grant Automation permission first)
#
# Usage:
#   bash deploy/install.sh [--venv-python /path/to/python3]
#
# On Linux the launchd section is skipped; nothing is installed automatically.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BRIDGE_REPO="$(dirname "$SCRIPT_DIR")"

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

BIN_DIR="${HOME}/.local/bin"
LIB_DIR="${HOME}/.local/lib/mac_notes_bridge"
PLIST_SRC="${SCRIPT_DIR}/com.homunculus.mac_notes_bridge.plist"
PLIST_DST="${HOME}/Library/LaunchAgents/com.homunculus.mac_notes_bridge.plist"
VENV_PYTHON="${1:-python3}"

# Handle --venv-python flag
if [[ "${1:-}" == "--venv-python" && -n "${2:-}" ]]; then
    VENV_PYTHON="$2"
fi

# ---------------------------------------------------------------------------
# Create directories
# ---------------------------------------------------------------------------

mkdir -p "$BIN_DIR" "$LIB_DIR"
echo "[install] Created $BIN_DIR and $LIB_DIR"

# ---------------------------------------------------------------------------
# Create venv and install mac-notes-bridge (editable)
# (boot volume so launchd can exec from here)
# ---------------------------------------------------------------------------

BRIDGE_VENV="${LIB_DIR}/venv"
if [ ! -d "$BRIDGE_VENV" ]; then
    echo "[install] Creating venv at $BRIDGE_VENV"
    "$VENV_PYTHON" -m venv "$BRIDGE_VENV"
fi

echo "[install] Installing mac-notes-bridge into $BRIDGE_VENV"
"$BRIDGE_VENV/bin/pip" install --quiet -e "$BRIDGE_REPO"
echo "[install] Package installed."

# ---------------------------------------------------------------------------
# Write the entry-point shell script to ~/.local/bin/
# ---------------------------------------------------------------------------

ENTRY_SH="${BIN_DIR}/mac_notes_bridge.sh"
cat > "$ENTRY_SH" <<'SHEOF'
#!/bin/bash
# Auto-generated by install.sh — do not edit by hand.
exec "${HOME}/.local/lib/mac_notes_bridge/venv/bin/python" -m mac_notes_bridge.watcher "$@"
SHEOF
chmod +x "$ENTRY_SH"
echo "[install] Entry point written to $ENTRY_SH"

# ---------------------------------------------------------------------------
# Install launchd plist (macOS only) — do NOT load it yet
# ---------------------------------------------------------------------------

if [[ "$(uname)" == "Darwin" ]]; then
    mkdir -p "${HOME}/Library/LaunchAgents"
    cp "$PLIST_SRC" "$PLIST_DST"
    # Patch the hardcoded /Users/fourierflight to the actual $HOME
    sed -i '' "s|/Users/fourierflight/|${HOME}/|g" "$PLIST_DST"
    echo "[install] Plist installed at $PLIST_DST"
    echo ""
    echo "======================================================================"
    echo "  IMPORTANT: Do not load the plist yet!"
    echo "  You must first create the 'Homunculus' folder in Notes.app under"
    echo "  the iCloud account. See docs/FIRST_RUN.md Step 1."
    echo ""
    echo "  Then load the plist:"
    echo "    launchctl load $PLIST_DST"
    echo ""
    echo "  macOS will prompt for Automation permission to control Notes.app."
    echo "  Click Allow."
    echo ""
    echo "  Watch logs:"
    echo "    tail -f /tmp/mac_notes_bridge.log"
    echo ""
    echo "  See docs/FIRST_RUN.md for the full walkthrough."
    echo "======================================================================"
else
    echo ""
    echo "======================================================================"
    echo "  Linux detected — launchd is not available."
    echo ""
    echo "  The bridge is Mac-only (AppleScript / Notes.app)."
    echo "  On Linux, Herman still works; only the Notes sync is unavailable."
    echo "======================================================================"
fi

# ---------------------------------------------------------------------------
# Verify plutil (macOS only)
# ---------------------------------------------------------------------------

if [[ "$(uname)" == "Darwin" ]]; then
    if plutil -lint "$PLIST_DST" >/dev/null 2>&1; then
        echo "[install] plutil lint: OK"
    else
        echo "[install] WARNING: plutil found issues in the plist — check $PLIST_DST"
    fi
fi

echo ""
echo "[install] Done. See docs/FIRST_RUN.md for next steps."
