#!/usr/bin/env python3
"""
generate_dashboard.py — Standalone dashboard note regenerator.

Regenerates three read-only Markdown files under journal/_dashboard/:
  - tasks-today.md     Open tasks (pending/in_progress/blocked), grouped by status
  - recent-activity.md Last 20 rows from activity_log, newest first
  - task-index.md      All open tasks grouped by team member

Run directly:
  python scripts/generate_dashboard.py

Invoked by sync_journal.py on DB change. The watcher deliberately ignores
writes to journal/_dashboard/ so these files never trigger a sync-to-DB loop.

AUTO-GENERATED — do not edit by hand. Changes will be overwritten.
"""

import sqlite3
import os
import sys
from datetime import datetime, timezone

# ── Paths ──────────────────────────────────────────────────────────────────
REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DB_PATH = os.path.join(REPO_ROOT, "db", "workspace.db")
DASHBOARD_DIR = os.path.join(REPO_ROOT, "journal", "_dashboard")

# ── DB helpers ─────────────────────────────────────────────────────────────

def open_db():
    """Open the DB with Reed's standard PRAGMAs. isolation_level=None = autocommit."""
    conn = sqlite3.connect(DB_PATH, isolation_level=None, timeout=10)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA foreign_keys = ON;")
    conn.execute("PRAGMA journal_mode = WAL;")
    conn.execute("PRAGMA busy_timeout = 5000;")
    conn.execute("PRAGMA temp_store = MEMORY;")
    return conn


def now_utc() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def now_display() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

# ── Frontmatter header ─────────────────────────────────────────────────────

def auto_header(title: str) -> str:
    return (
        f"---\n"
        f"title: \"{title}\"\n"
        f"read_only: true\n"
        f"generated_at: \"{now_utc()}\"\n"
        f"---\n\n"
        f"> [!warning] AUTO-GENERATED — do not edit by hand.\n"
        f"> Regenerated by `scripts/generate_dashboard.py` at {now_display()}.\n\n"
    )

# ── tasks-today.md ─────────────────────────────────────────────────────────

STATUS_ORDER = ["urgent", "high", "normal", "low"]
STATUS_LABELS = {
    "in_progress": "In Progress",
    "pending": "Pending",
    "blocked": "Blocked",
}
PRIORITY_EMOJI = {
    "urgent": "🔴",
    "high": "🟠",
    "normal": "🟡",
    "low": "⚪",
}


def generate_tasks_today(conn: sqlite3.Connection) -> str:
    rows = conn.execute(
        """
        SELECT t.id, t.title, t.status, t.priority,
               COALESCE(m.name, 'Unassigned') AS assigned_to,
               t.due_date, t.created_at
        FROM tasks t
        LEFT JOIN team_members m ON t.assigned_to = m.id
        WHERE t.status IN ('pending', 'in_progress', 'blocked')
        ORDER BY
            CASE t.priority WHEN 'urgent' THEN 1 WHEN 'high' THEN 2
                            WHEN 'normal' THEN 3 WHEN 'low' THEN 4 END,
            t.id
        """,
        [],
    ).fetchall()

    out = auto_header("Tasks Today")
    out += f"# Open Tasks\n\n"

    if not rows:
        out += "_No open tasks right now. 🎉_\n"
        return out

    # Group by status
    by_status: dict[str, list] = {"in_progress": [], "blocked": [], "pending": []}
    for r in rows:
        by_status.setdefault(r["status"], []).append(r)

    for status_key, label in STATUS_LABELS.items():
        group = by_status.get(status_key, [])
        if not group:
            continue
        out += f"## {label}\n\n"
        out += "| # | Title | Priority | Assigned To | Due |\n"
        out += "|---|-------|----------|-------------|-----|\n"
        for r in group:
            pri = PRIORITY_EMOJI.get(r["priority"], "") + " " + r["priority"]
            due = r["due_date"] or "—"
            out += f"| {r['id']} | {r['title']} | {pri} | {r['assigned_to']} | {due} |\n"
        out += "\n"

    return out


# ── recent-activity.md ─────────────────────────────────────────────────────

def generate_recent_activity(conn: sqlite3.Connection) -> str:
    rows = conn.execute(
        """
        SELECT id, actor, action, entity_type, details, created_at
        FROM activity_log
        ORDER BY id DESC
        LIMIT 20
        """,
        [],
    ).fetchall()

    out = auto_header("Recent Activity")
    out += "# Recent Activity (last 20 events)\n\n"

    if not rows:
        out += "_No activity recorded yet._\n"
        return out

    out += "| When (UTC) | Actor | Action | Type | Details |\n"
    out += "|------------|-------|--------|------|---------|\n"
    for r in rows:
        ts = r["created_at"] or "—"
        details = (r["details"] or "").replace("|", "\\|").replace("\n", " ")
        if len(details) > 120:
            details = details[:117] + "…"
        out += f"| {ts} | {r['actor']} | {r['action']} | {r['entity_type'] or '—'} | {details} |\n"

    return out


# ── task-index.md ──────────────────────────────────────────────────────────

def _task_count_summary(conn: sqlite3.Connection) -> str:
    """Return a one-line summary of task counts by status, e.g.:
    Tasks: 427 total — 420 done, 3 cancelled, 3 in_progress, 1 pending
    Driven entirely from the DB so new statuses appear automatically.
    """
    total = conn.execute("SELECT COUNT(*) FROM tasks").fetchone()[0]
    by_status = conn.execute(
        "SELECT status, COUNT(*) AS cnt FROM tasks GROUP BY status ORDER BY cnt DESC"
    ).fetchall()
    parts = ", ".join(f"{row[1]} {row[0]}" for row in by_status)
    return f"**Tasks: {total} total — {parts}**\n\n"


def generate_task_index(conn: sqlite3.Connection) -> str:
    rows = conn.execute(
        """
        SELECT t.id, t.title, t.status, t.priority,
               COALESCE(m.name, 'Unassigned') AS assigned_to,
               t.due_date
        FROM tasks t
        LEFT JOIN team_members m ON t.assigned_to = m.id
        WHERE t.status IN ('pending', 'in_progress', 'blocked')
        ORDER BY COALESCE(m.name, 'Unassigned'), t.id
        """,
        [],
    ).fetchall()

    out = auto_header("Task Index")
    out += "# Task Index (open tasks by team member)\n\n"
    out += _task_count_summary(conn)

    if not rows:
        out += "_No open tasks right now._\n"
        return out

    # Group by team member
    by_member: dict[str, list] = {}
    for r in rows:
        by_member.setdefault(r["assigned_to"], []).append(r)

    for member, tasks in sorted(by_member.items()):
        out += f"## {member}\n\n"
        out += "| # | Title | Status | Priority | Due |\n"
        out += "|---|-------|--------|----------|-----|\n"
        for r in tasks:
            pri = PRIORITY_EMOJI.get(r["priority"], "") + " " + r["priority"]
            due = r["due_date"] or "—"
            out += f"| {r['id']} | {r['title']} | {r['status']} | {pri} | {due} |\n"
        out += "\n"

    return out


# ── Write helper ───────────────────────────────────────────────────────────

def write_dashboard_file(path: str, content: str) -> None:
    """Atomic write: write to .tmp then rename, so Obsidian sees a complete file."""
    tmp = path + ".tmp"
    with open(tmp, "w", encoding="utf-8") as f:
        f.write(content)
    os.replace(tmp, path)
    print(f"  [dashboard] wrote {os.path.relpath(path, REPO_ROOT)}")


# ── Main ───────────────────────────────────────────────────────────────────

def generate_all() -> None:
    os.makedirs(DASHBOARD_DIR, exist_ok=True)

    conn = open_db()
    try:
        tasks_today = generate_tasks_today(conn)
        recent_activity = generate_recent_activity(conn)
        task_index = generate_task_index(conn)
    finally:
        conn.close()

    write_dashboard_file(os.path.join(DASHBOARD_DIR, "tasks-today.md"), tasks_today)
    write_dashboard_file(os.path.join(DASHBOARD_DIR, "recent-activity.md"), recent_activity)
    write_dashboard_file(os.path.join(DASHBOARD_DIR, "task-index.md"), task_index)

    print(f"[dashboard] Done — regenerated at {now_display()}")


if __name__ == "__main__":
    generate_all()
