#!/bin/bash
# mac_reminders_bridge v0.1.0 install script
#
# Installs the bridge to the boot volume (required — repo lives on /Volumes/GIT
# which is nosuid; launchd cannot exec scripts from there).
#
# What this does:
#   1. Creates ~/.local/lib/mac_reminders_bridge/venv (Python venv on boot volume)
#   2. pip-installs mac-reminders-bridge (editable) from the repo
#   3. Writes ~/.local/bin/mac_reminders_bridge.sh (entry point)
#   4. Copies the launchd plist to ~/Library/LaunchAgents/ (macOS only)
#      - patches /Users/fourierflight → $HOME
#      - does NOT load the plist (you must create the Reminders list and grant
#        Automation permission first — see docs/FIRST_RUN.md)
#
# Usage:
#   bash deploy/install.sh [--venv-python /path/to/python3]
#
# On Linux the launchd section is skipped; the venv + entry point are still installed.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BRIDGE_REPO="$(dirname "$SCRIPT_DIR")"

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

BIN_DIR="${HOME}/.local/bin"
LIB_DIR="${HOME}/.local/lib/mac_reminders_bridge"
PLIST_SRC="${SCRIPT_DIR}/com.homunculus.mac_reminders_bridge.plist"
PLIST_DST="${HOME}/Library/LaunchAgents/com.homunculus.mac_reminders_bridge.plist"
VENV_PYTHON="python3"

# Handle --venv-python flag
if [[ "${1:-}" == "--venv-python" && -n "${2:-}" ]]; then
    VENV_PYTHON="$2"
fi

# ---------------------------------------------------------------------------
# Create directories
# ---------------------------------------------------------------------------

mkdir -p "$BIN_DIR" "$LIB_DIR"
echo "[install] Created $BIN_DIR and $LIB_DIR"

# ---------------------------------------------------------------------------
# Create venv and install mac-reminders-bridge (editable)
# (boot volume so launchd can exec from here)
# ---------------------------------------------------------------------------

BRIDGE_VENV="${LIB_DIR}/venv"
if [ ! -d "$BRIDGE_VENV" ]; then
    echo "[install] Creating venv at $BRIDGE_VENV"
    "$VENV_PYTHON" -m venv "$BRIDGE_VENV"
fi

echo "[install] Installing mac-reminders-bridge into $BRIDGE_VENV"
"$BRIDGE_VENV/bin/pip" install --quiet -e "$BRIDGE_REPO"
echo "[install] Package installed."

# ---------------------------------------------------------------------------
# Write the entry-point shell script to ~/.local/bin/
# ---------------------------------------------------------------------------

ENTRY_SH="${BIN_DIR}/mac_reminders_bridge.sh"
cat > "$ENTRY_SH" <<'SHEOF'
#!/bin/bash
# Auto-generated by install.sh — do not edit by hand.
exec "${HOME}/.local/lib/mac_reminders_bridge/venv/bin/python" -m mac_reminders_bridge.watcher "$@"
SHEOF
chmod +x "$ENTRY_SH"
echo "[install] Entry point written to $ENTRY_SH"

# ---------------------------------------------------------------------------
# Install launchd plist (macOS only) — do NOT load it yet
# ---------------------------------------------------------------------------

if [[ "$(uname)" == "Darwin" ]]; then
    mkdir -p "${HOME}/Library/LaunchAgents"
    cp "$PLIST_SRC" "$PLIST_DST"
    # Patch the hardcoded /Users/fourierflight to the actual $HOME
    sed -i '' "s|/Users/fourierflight/|${HOME}/|g" "$PLIST_DST"
    echo "[install] Plist installed at $PLIST_DST"
    echo ""
    echo "======================================================================"
    echo "  IMPORTANT: Do not load the plist yet!"
    echo "  You must create the Reminders list and grant Automation permission FIRST."
    echo ""
    echo "  Steps:"
    echo "    1. Open Reminders.app, choose File → New List"
    echo "    2. Select the iCloud account, name it exactly: Homunculus"
    echo "    3. Then run:"
    echo "       launchctl load $PLIST_DST"
    echo "    4. macOS will prompt for Automation permission — click OK"
    echo "    5. Confirm it started:"
    echo "       launchctl list | grep mac_reminders_bridge"
    echo "       tail -f /tmp/mac_reminders_bridge.log"
    echo ""
    echo "  See docs/FIRST_RUN.md for the full walkthrough."
    echo "======================================================================"
else
    echo ""
    echo "======================================================================"
    echo "  Linux detected — launchd is not available."
    echo ""
    echo "  The bridge's AppleScript layer is Mac-only (Reminders.app)."
    echo "  On Linux, Herman still works; only the Reminders sync is unavailable."
    echo ""
    echo "  A systemd unit file is available at:"
    echo "    ${SCRIPT_DIR}/mac-reminders-bridge.service"
    echo "======================================================================"
fi

# ---------------------------------------------------------------------------
# Verify plutil (macOS only)
# ---------------------------------------------------------------------------

if [[ "$(uname)" == "Darwin" ]]; then
    if plutil -lint "$PLIST_DST" >/dev/null 2>&1; then
        echo "[install] plutil lint: OK"
    else
        echo "[install] WARNING: plutil found issues in the plist — check $PLIST_DST"
    fi
fi

echo ""
echo "[install] Done. See docs/FIRST_RUN.md for next steps."
